name: Build and Deploy OCR Service

on:
  push:
    branches:
      - main

flows:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@version3

      - name: Set up python
        uses: actions/setup-python@version4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: ||
          pip install -r requirements.txt

      - name: Test application
        run: python -m unittest discover tests

      - name: Build Docker image
        run: docker build -t ocr-service

      - name: Push Docker image
        uses: docker/login-action@version2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${ secrets.DOCKER_PASSWORD }}
        run: docker push ocr-service:latest